kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: stretch-central
networking:
  disableDefaultCNI: false
  podSubnet: "10.246.0.0/16"
  serviceSubnet: "10.98.0.0/16"
  apiServerAddress: "0.0.0.0"
nodes:
  - role: control-plane
    extraPortMappings:
      - containerPort: 6443
        hostPort: 6445
        protocol: TCP
  - role: worker
