= Transform JSON Messages into a New Topic using JQ
:page-layout: lab
:env-docker: true
:page-categories: Development, Stream Processing, Data Transforms
:description: Filter messages from one topic into another using jq and data transforms.
// Set up attributes to hold the latest version of Redpanda and Redpanda Console.
// For GitHub, hard-code the latest version to these values:
ifndef::env-site[]
:latest-redpanda-version: 23.3.8
:latest-console-version: 2.4.0
endif::[]
// For the docs site, use the built-in attributes that store the latest version as fetched from GitHub releases.
ifdef::env-site[]
:latest-redpanda-version: {full-version}
// All pages already have access to {latest-console-version} on the docs site.
endif::[]

This lab contains a reusable data transform using `jaq` a rust version of the the popular `jq` command line JSON processor.

See the jq manual for more information on how to write a filter: https://jqlang.github.io/jq/manual/

== Prerequisites

You must have the following:

- At least version 1.75 of https://rustup.rs/[Rust^] installed on your host machine.
- link:https://docs.redpanda.com/current/get-started/rpk-install/[Install `rpk`] on your host machine.
- https://docs.docker.com/compose/install/[Docker and Docker Compose] installed on your host machine.

== Run the lab

. Clone this repository:
+
```bash
git clone https://github.com/redpanda-data/redpanda-labs.git
```

. Change into the `data-transforms/jq/` directory:
+
[,bash]
----
cd redpanda-labs/data-transforms/jq
----

. Set the `REDPANDA_VERSION` environment variable to at least version 23.3.1. Data transforms was introduced in this version. For all available versions, see the https://github.com/redpanda-data/redpanda/releases[GitHub releases].
+
For example:
+
[,bash,subs="attributes+"]
----
export REDPANDA_VERSION={latest-redpanda-version}
----

. Set the `REDPANDA_CONSOLE_VERSION` environment variable to the version of Redpanda Console that you want to run. For all available versions, see the https://github.com/redpanda-data/redpanda/releases[GitHub releases].
+
For example:
+
[,bash,subs="attributes+"]
----
export REDPANDA_CONSOLE_VERSION={latest-console-version}
----

. Start Redpanda in Docker by running the following command:
+
```bash
docker compose up -d
```

. Set up your rpk profile:
+
```bash
rpk profile create regex --from-profile profile.yml
```

. Create the required topics:
+
```bash
rpk topic create src sink
```

. Deploy the transforms function:
+
```bash
rpk transform build
rpk transform deploy --var=FILTER="del(.email)" --input-topic=src --output-topic=sink
```
+
This example accepts the following environment variable:
+
- `FILTER` (*required*): The jq expression that will run on each record's value.

. Run `rpk topic produce`:
+
[,bash]
----
rpk topic produce src
----

. Paste the following into the prompt and press kbd:[Ctrl + D] to exit:
+
```json
{"foo": 42, "email": "help@example.com"}
```

. Consume the sink topic to see the email address was deleted and the record produced to the sink topic:
+
```bash
rpk topic consume sink
```
+
[json, role="no-copy"]
----
{
  "topic": "sink",
  "value": "{\"foo\":42}",
  "timestamp": 1707749921393,
  "partition": 0,
  "offset": 0
}
----

You can also see this in http://localhost:8080/topics/sink?p=-1&s=50&o=-1#messages[Redpanda Console].

== Clean up

To shut down and delete the containers along with all your cluster data:

```bash
docker compose down -v
```
