= Filter Messages into a New Topic using a Regex
:page-layout: lab
:env-docker: true
:page-categories: Development, Stream Processing, Data Transforms
:description: Filter messages from one topic into another using regular expressions (regex) and data transforms.
// Set up attributes to hold the latest version of Redpanda and Redpanda Console.
// For GitHub, hard-code the latest version to these values:
ifndef::env-site[]
:latest-redpanda-version: 23.3.5
:latest-console-version: 2.4.0
endif::[]
// For the docs site, use the built-in attributes that store the latest version as fetched from GitHub releases.
ifdef::env-site[]
:latest-redpanda-version: {full-version}
// All pages already have access to {latest-console-version} on the docs site.
endif::[]

This is an example of how to filter messages from one topic into another using regular expressions (regex) and Redpanda data transforms. If a source topic contains a key or value that matches the regex, it will be produced to the sink topic.

Regexes are implemented using Go's `regexp` library, which uses the same syntax as RE2.
See the https://github.com/google/re2/wiki/Syntax[RE2 wiki] for help with syntax.

== Prerequisites

You must have the following:

- At least version 1.20 of https://go.dev/doc/install[Go^] installed on your host machine.
- link:https://docs.redpanda.com/current/get-started/rpk-install/[Install `rpk`] on your host machine.
- https://docs.docker.com/compose/install/[Docker and Docker Compose] installed on your host machine.

== Run the lab

. Clone this repository:
+
```bash
git clone https://github.com/redpanda-data/redpanda-labs.git
```

. Change into the `data-transforms/regex/` directory:
+
[,bash]
----
cd redpanda-labs/data-transforms/regex
----

. Set the `REDPANDA_VERSION` environment variable to at least version 23.3.1. Data transforms was introduced in this version. For all available versions, see the https://github.com/redpanda-data/redpanda/releases[GitHub releases].
+
For example:
+
[,bash,subs="attributes+"]
----
export REDPANDA_VERSION={latest-redpanda-version}
----

. Set the `REDPANDA_CONSOLE_VERSION` environment variable to the version of Redpanda Console that you want to run. For all available versions, see the https://github.com/redpanda-data/redpanda/releases[GitHub releases].
+
For example:
+
[,bash,subs="attributes+"]
----
export REDPANDA_CONSOLE_VERSION={latest-console-version}
----

. Start Redpanda in Docker by running the following command:
+
```bash
docker compose up -d
```

. Set up your rpk profile:
+
```bash
rpk profile create regex --from-profile profile.yml
```

. Create the required topics:
+
```bash
rpk topic create src sink
```

. Deploy the transforms function:
+
```bash
rpk transform build
rpk transform deploy --var=PATTERN="\\b[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Z|a-z]{2,}\\b" --var=MATCH_VALUE=true --input-topic=src --output-topic=sink
```
+
This example accepts the following environment variables:
+
- `PATTERN` (*required*): The regex to match against records. Here, the regex finds messages containing email addresses.
- `MATCH_VALUE`: By default, the regex matches record keys, but if set to `true`, the regex will match values.

. Run `rpk topic produce`:
+
[,bash]
----
rpk topic produce src
----

. Paste the following into the prompt and press kbd:[Ctrl + C] to exit:
+
```json
Hello, please contact us at help@example.com.
```

. Consume the sink topic to see the email address was extracted and produced to the sink topic:
+
```bash
rpk topic consume sink
```
+
[json, role="no-copy"]
----
{
  "topic": "sink",
  "value": "Hello, please contact us at help@example.com.",
  "timestamp": 1707749921393,
  "partition": 0,
  "offset": 0
}
----

You can also see this in http://localhost:8080/topics/sink?p=-1&s=50&o=-1#messages[Redpanda Console].

== Clean up

To shut down and delete the containers along with all your cluster data:

```bash
docker compose down -v
```
