= Enable Plain Login Authentication for Redpanda Console
:env-docker: true
:page-categories: Security, Management, Redpanda Console
:description: Deploy Redpanda Console with a plain login provider so that users of Redpanda Console must log in with a username and password.
:page-layout: lab
// Set up attributes to hold the latest version of Redpanda and Redpanda Console.
// For GitHub, hard-code the latest version to these values:
ifndef::env-site[]
:latest-redpanda-version: 24.2.6
:latest-console-version: 2.7.1
endif::[]
// For the docs site, use the built-in attributes that store the latest version as fetched from GitHub releases.
ifdef::env-site[]
:latest-redpanda-version: {full-version}
// All pages already have access to {latest-console-version} on the docs site.
endif::[]

This Docker Compose file configures Redpanda Console with a plain login provider so that users of Redpanda Console must log in with a username and password.

This example uses features that require a license key for Redpanda Enterprise Edition. The license key is uploaded to the Redpanda broker through a separate container called `redpandarpk`. This container executes the `rpk cluster license set` command to load the license key from the given filepath. To request a trial license, to extend your trial period, or to purchase an Enterprise Edition license,
contact https://redpanda.com/try-redpanda?section=enterprise-trial[Redpanda Sales^].

== Prerequisites

You must have https://docs.docker.com/compose/install/[Docker and Docker Compose] installed on your host machine.

== Run the lab

// For GitHub, provide instructions for cloning the repo.
ifndef::env-site[]
. Clone this repository:
+
```bash
git clone https://github.com/redpanda-data/redpanda-labs.git
```

. Change into the `docker-compose/console-plain-login/` directory:
+
[,bash]
----
cd redpanda-labs/docker-compose/console-plain-login
----
endif::[]
// For the docs site, provide a download link since we have symlinked the Docker Compose file into the attachments directory of the Antora structure. See https://docs.antora.org/antora/latest/page/attachments/
ifdef::env-site[]
. xref:redpanda-labs:docker-compose:attachment$console-plain-login/docker-compose.yml[Download] the following Docker Compose file on your local file system.
+
NOTE: If you are running on an ARM-based device such as the Apple M1 chip, uncomment the `platform: 'linux/amd64'` lines.
+
.Reveal the Docker Compose file
[%collapsible]
====
.`docker-compose.yml`
[,yaml,subs="attributes+"]
----
include::redpanda-labs:docker-compose:attachment$console-plain-login/docker-compose.yml[]
----
====
endif::[]

. Set the `REDPANDA_VERSION` environment variable to the version of Redpanda that you want to run. For all available versions, see the https://github.com/redpanda-data/redpanda/releases[GitHub releases].
+
For example:
+
[,bash,subs="attributes+"]
----
export REDPANDA_VERSION={latest-redpanda-version}
----

. Set the `REDPANDA_CONSOLE_VERSION` environment variable to the version of Redpanda Console that you want to run. For all available versions, see the https://github.com/redpanda-data/redpanda/releases[GitHub releases].
+
For example:
+
[,bash,subs="attributes+"]
----
export REDPANDA_CONSOLE_VERSION={latest-console-version}
----

. Save your license key to `license/redpanda.license` in the same location as your Docker Compose file. Or, to use another location, update the license paths in the Docker Compose file to another directory that contains your license key.

. Run the following in the directory where you saved the Docker Compose file:
+
```bash
docker compose up -d
```

. Open Redpanda Console at http://localhost:8080[localhost:8080^] and log in with the credentials for `john` or `jane`, which are defined in the Docker Compose file in the `CONSOLE_CONFIG_FILE` environment variable.

== Clean up

To shut down and delete the containers along with all your cluster data:

```bash
docker compose down -v
```