= Filter JSON Messages into a New Topic using JQ
:page-layout: lab
:env-docker: true
:page-categories: Development, Stream Processing
:description: Filter JSON messages in topics using data transforms.

This is an example of how to filter JSON messages in topics using xref:ROOT:develop:data-transforms/how-transforms-work.adoc[Redpanda data transforms]. The transforms function uses the https://jqlang.github.io/jq/manual/[`jq`] command-line JSON processor to read JSON messages in an input topic and produce the results of the filter to an output topic.

include::data-transforms:partial$prerequisites.adoc[]

- A Unix machine.

== Run the example

. {repository}fork[Fork the `redpanda-labs` repository] and clone your local fork.

. Change into the `docker-compose/single-broker/` directory:
+
[,bash]
----
cd redpanda-labs/docker-compose/single-broker
----

. Start Redpanda in Docker by running the following command:
+
```bash
docker compose up -d
```

. Change into the `data-transforms/jq/` directory:
+
[,bash]
----
cd ../../data-transforms/jq
----

. Deploy the transforms function:
+
```bash
docker exec -it redpanda-0 rpk transform deploy jq.wasm --var=FILTER='.myfilter' --input-topic=src --output-topic=sink
```
+
This example accepts the following environment variables:
+
- `FILTER` (*required*): The expression that `jq` will execute against record values.

include::docker-compose:partial$docker-clean-up.adoc[]
