// Game event contract for the multiplayer-gaming solution.
//
// Every record on game.player-events, game.match-events, and
// game.achievements is one GameEvent. The envelope carries the identity and
// time of the event; the oneof carries the payload. Every record on
// game.leaderboard is one LeaderboardEntry, a player's current total.
// Registered in Schema Registry as a Protobuf schema under the subjects
// <topic>-value with BACKWARD compatibility, so a consumer compiled against
// an older version can always read what a newer producer writes.
//
// This file is version 2 of the schema: it adds the optional `region` field
// and the LeaderboardEntry message. proto/history/game_events.v1.proto is the
// version the solution starts from.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: game_events.proto

package gamepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// tag::envelope[]
type GameEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique per event. The Postgres sink uses it as the primary key, so a
	// redelivered record inserts nothing twice.
	EventId string `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	// Record key on game.player-events and game.achievements. Every event of one
	// player lands on one partition, in order.
	PlayerId string `protobuf:"bytes,2,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	// Record key on game.match-events.
	MatchId    string                 `protobuf:"bytes,3,opt,name=match_id,json=matchId,proto3" json:"match_id,omitempty"`
	OccurredAt *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=occurred_at,json=occurredAt,proto3" json:"occurred_at,omitempty"`
	// Added in version 2. Old consumers ignore it; new consumers see it unset on
	// old records. That is what BACKWARD compatibility guarantees.
	Region *string `protobuf:"bytes,5,opt,name=region,proto3,oneof" json:"region,omitempty"`
	// Types that are valid to be assigned to Event:
	//
	//	*GameEvent_PlayerJoined
	//	*GameEvent_PlayerLeft
	//	*GameEvent_MatchStarted
	//	*GameEvent_MatchEnded
	//	*GameEvent_ScoreChanged
	//	*GameEvent_ItemAcquired
	//	*GameEvent_AchievementUnlocked
	Event         isGameEvent_Event `protobuf_oneof:"event"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GameEvent) Reset() {
	*x = GameEvent{}
	mi := &file_game_events_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameEvent) ProtoMessage() {}

func (x *GameEvent) ProtoReflect() protoreflect.Message {
	mi := &file_game_events_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameEvent.ProtoReflect.Descriptor instead.
func (*GameEvent) Descriptor() ([]byte, []int) {
	return file_game_events_proto_rawDescGZIP(), []int{0}
}

func (x *GameEvent) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *GameEvent) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *GameEvent) GetMatchId() string {
	if x != nil {
		return x.MatchId
	}
	return ""
}

func (x *GameEvent) GetOccurredAt() *timestamppb.Timestamp {
	if x != nil {
		return x.OccurredAt
	}
	return nil
}

func (x *GameEvent) GetRegion() string {
	if x != nil && x.Region != nil {
		return *x.Region
	}
	return ""
}

func (x *GameEvent) GetEvent() isGameEvent_Event {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *GameEvent) GetPlayerJoined() *PlayerJoined {
	if x != nil {
		if x, ok := x.Event.(*GameEvent_PlayerJoined); ok {
			return x.PlayerJoined
		}
	}
	return nil
}

func (x *GameEvent) GetPlayerLeft() *PlayerLeft {
	if x != nil {
		if x, ok := x.Event.(*GameEvent_PlayerLeft); ok {
			return x.PlayerLeft
		}
	}
	return nil
}

func (x *GameEvent) GetMatchStarted() *MatchStarted {
	if x != nil {
		if x, ok := x.Event.(*GameEvent_MatchStarted); ok {
			return x.MatchStarted
		}
	}
	return nil
}

func (x *GameEvent) GetMatchEnded() *MatchEnded {
	if x != nil {
		if x, ok := x.Event.(*GameEvent_MatchEnded); ok {
			return x.MatchEnded
		}
	}
	return nil
}

func (x *GameEvent) GetScoreChanged() *ScoreChanged {
	if x != nil {
		if x, ok := x.Event.(*GameEvent_ScoreChanged); ok {
			return x.ScoreChanged
		}
	}
	return nil
}

func (x *GameEvent) GetItemAcquired() *ItemAcquired {
	if x != nil {
		if x, ok := x.Event.(*GameEvent_ItemAcquired); ok {
			return x.ItemAcquired
		}
	}
	return nil
}

func (x *GameEvent) GetAchievementUnlocked() *AchievementUnlocked {
	if x != nil {
		if x, ok := x.Event.(*GameEvent_AchievementUnlocked); ok {
			return x.AchievementUnlocked
		}
	}
	return nil
}

type isGameEvent_Event interface {
	isGameEvent_Event()
}

type GameEvent_PlayerJoined struct {
	PlayerJoined *PlayerJoined `protobuf:"bytes,10,opt,name=player_joined,json=playerJoined,proto3,oneof"`
}

type GameEvent_PlayerLeft struct {
	PlayerLeft *PlayerLeft `protobuf:"bytes,11,opt,name=player_left,json=playerLeft,proto3,oneof"`
}

type GameEvent_MatchStarted struct {
	MatchStarted *MatchStarted `protobuf:"bytes,12,opt,name=match_started,json=matchStarted,proto3,oneof"`
}

type GameEvent_MatchEnded struct {
	MatchEnded *MatchEnded `protobuf:"bytes,13,opt,name=match_ended,json=matchEnded,proto3,oneof"`
}

type GameEvent_ScoreChanged struct {
	ScoreChanged *ScoreChanged `protobuf:"bytes,14,opt,name=score_changed,json=scoreChanged,proto3,oneof"`
}

type GameEvent_ItemAcquired struct {
	ItemAcquired *ItemAcquired `protobuf:"bytes,15,opt,name=item_acquired,json=itemAcquired,proto3,oneof"`
}

type GameEvent_AchievementUnlocked struct {
	AchievementUnlocked *AchievementUnlocked `protobuf:"bytes,16,opt,name=achievement_unlocked,json=achievementUnlocked,proto3,oneof"`
}

func (*GameEvent_PlayerJoined) isGameEvent_Event() {}

func (*GameEvent_PlayerLeft) isGameEvent_Event() {}

func (*GameEvent_MatchStarted) isGameEvent_Event() {}

func (*GameEvent_MatchEnded) isGameEvent_Event() {}

func (*GameEvent_ScoreChanged) isGameEvent_Event() {}

func (*GameEvent_ItemAcquired) isGameEvent_Event() {}

func (*GameEvent_AchievementUnlocked) isGameEvent_Event() {}

// tag::payloads[]
type PlayerJoined struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DisplayName   string                 `protobuf:"bytes,1,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerJoined) Reset() {
	*x = PlayerJoined{}
	mi := &file_game_events_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerJoined) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerJoined) ProtoMessage() {}

func (x *PlayerJoined) ProtoReflect() protoreflect.Message {
	mi := &file_game_events_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerJoined.ProtoReflect.Descriptor instead.
func (*PlayerJoined) Descriptor() ([]byte, []int) {
	return file_game_events_proto_rawDescGZIP(), []int{1}
}

func (x *PlayerJoined) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

// One per participant when a match ends, keyed by player_id, so a consumer
// that owns a player's partition sees that player's match results.
type PlayerLeft struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Won           bool                   `protobuf:"varint,1,opt,name=won,proto3" json:"won,omitempty"`
	FinalScore    int64                  `protobuf:"varint,2,opt,name=final_score,json=finalScore,proto3" json:"final_score,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerLeft) Reset() {
	*x = PlayerLeft{}
	mi := &file_game_events_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerLeft) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerLeft) ProtoMessage() {}

func (x *PlayerLeft) ProtoReflect() protoreflect.Message {
	mi := &file_game_events_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerLeft.ProtoReflect.Descriptor instead.
func (*PlayerLeft) Descriptor() ([]byte, []int) {
	return file_game_events_proto_rawDescGZIP(), []int{2}
}

func (x *PlayerLeft) GetWon() bool {
	if x != nil {
		return x.Won
	}
	return false
}

func (x *PlayerLeft) GetFinalScore() int64 {
	if x != nil {
		return x.FinalScore
	}
	return 0
}

type MatchStarted struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerIds     []string               `protobuf:"bytes,1,rep,name=player_ids,json=playerIds,proto3" json:"player_ids,omitempty"`
	Mode          string                 `protobuf:"bytes,2,opt,name=mode,proto3" json:"mode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MatchStarted) Reset() {
	*x = MatchStarted{}
	mi := &file_game_events_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MatchStarted) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchStarted) ProtoMessage() {}

func (x *MatchStarted) ProtoReflect() protoreflect.Message {
	mi := &file_game_events_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatchStarted.ProtoReflect.Descriptor instead.
func (*MatchStarted) Descriptor() ([]byte, []int) {
	return file_game_events_proto_rawDescGZIP(), []int{3}
}

func (x *MatchStarted) GetPlayerIds() []string {
	if x != nil {
		return x.PlayerIds
	}
	return nil
}

func (x *MatchStarted) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

type MatchEnded struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	PlayerIds       []string               `protobuf:"bytes,1,rep,name=player_ids,json=playerIds,proto3" json:"player_ids,omitempty"`
	WinnerPlayerId  string                 `protobuf:"bytes,2,opt,name=winner_player_id,json=winnerPlayerId,proto3" json:"winner_player_id,omitempty"`
	DurationSeconds int64                  `protobuf:"varint,3,opt,name=duration_seconds,json=durationSeconds,proto3" json:"duration_seconds,omitempty"`
	StartedAt       *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *MatchEnded) Reset() {
	*x = MatchEnded{}
	mi := &file_game_events_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MatchEnded) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchEnded) ProtoMessage() {}

func (x *MatchEnded) ProtoReflect() protoreflect.Message {
	mi := &file_game_events_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatchEnded.ProtoReflect.Descriptor instead.
func (*MatchEnded) Descriptor() ([]byte, []int) {
	return file_game_events_proto_rawDescGZIP(), []int{4}
}

func (x *MatchEnded) GetPlayerIds() []string {
	if x != nil {
		return x.PlayerIds
	}
	return nil
}

func (x *MatchEnded) GetWinnerPlayerId() string {
	if x != nil {
		return x.WinnerPlayerId
	}
	return ""
}

func (x *MatchEnded) GetDurationSeconds() int64 {
	if x != nil {
		return x.DurationSeconds
	}
	return 0
}

func (x *MatchEnded) GetStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartedAt
	}
	return nil
}

type ScoreChanged struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Positive or negative. The leaderboard service adds it to the player's
	// running total and publishes that total to game.leaderboard.
	Delta         int64  `protobuf:"varint,1,opt,name=delta,proto3" json:"delta,omitempty"`
	NewScore      int64  `protobuf:"varint,2,opt,name=new_score,json=newScore,proto3" json:"new_score,omitempty"`
	Reason        string `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScoreChanged) Reset() {
	*x = ScoreChanged{}
	mi := &file_game_events_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScoreChanged) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScoreChanged) ProtoMessage() {}

func (x *ScoreChanged) ProtoReflect() protoreflect.Message {
	mi := &file_game_events_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScoreChanged.ProtoReflect.Descriptor instead.
func (*ScoreChanged) Descriptor() ([]byte, []int) {
	return file_game_events_proto_rawDescGZIP(), []int{5}
}

func (x *ScoreChanged) GetDelta() int64 {
	if x != nil {
		return x.Delta
	}
	return 0
}

func (x *ScoreChanged) GetNewScore() int64 {
	if x != nil {
		return x.NewScore
	}
	return 0
}

func (x *ScoreChanged) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type ItemAcquired struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ItemId        string                 `protobuf:"bytes,1,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	Quantity      int32                  `protobuf:"varint,2,opt,name=quantity,proto3" json:"quantity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ItemAcquired) Reset() {
	*x = ItemAcquired{}
	mi := &file_game_events_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ItemAcquired) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ItemAcquired) ProtoMessage() {}

func (x *ItemAcquired) ProtoReflect() protoreflect.Message {
	mi := &file_game_events_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ItemAcquired.ProtoReflect.Descriptor instead.
func (*ItemAcquired) Descriptor() ([]byte, []int) {
	return file_game_events_proto_rawDescGZIP(), []int{6}
}

func (x *ItemAcquired) GetItemId() string {
	if x != nil {
		return x.ItemId
	}
	return ""
}

func (x *ItemAcquired) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

type AchievementUnlocked struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// hot_streak, first_win, veteran
	Achievement   string `protobuf:"bytes,1,opt,name=achievement,proto3" json:"achievement,omitempty"`
	Detail        string `protobuf:"bytes,2,opt,name=detail,proto3" json:"detail,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AchievementUnlocked) Reset() {
	*x = AchievementUnlocked{}
	mi := &file_game_events_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AchievementUnlocked) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AchievementUnlocked) ProtoMessage() {}

func (x *AchievementUnlocked) ProtoReflect() protoreflect.Message {
	mi := &file_game_events_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AchievementUnlocked.ProtoReflect.Descriptor instead.
func (*AchievementUnlocked) Descriptor() ([]byte, []int) {
	return file_game_events_proto_rawDescGZIP(), []int{7}
}

func (x *AchievementUnlocked) GetAchievement() string {
	if x != nil {
		return x.Achievement
	}
	return ""
}

func (x *AchievementUnlocked) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

// tag::leaderboard[]
// One record on game.leaderboard, keyed by player_id: the player's current
// total, not a change to it. The leaderboard service publishes a new entry
// after every score_changed, and the topic is compacted, so it converges to
// one live record per player. Any reader that consumes it from the start ends
// up with the full board, without replaying a single game event.
type LeaderboardEntry struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	PlayerId    string                 `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	DisplayName string                 `protobuf:"bytes,2,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	// Absolute total: the sum of every score_changed delta for this player.
	Score     int64                  `protobuf:"varint,3,opt,name=score,proto3" json:"score,omitempty"`
	UpdatedAt *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	// The game.player-events partition this player's events live on, and the
	// offset of the last one included in score. A service that takes over that
	// partition loads its players' entries from here and knows exactly where
	// each total stops.
	SourcePartition int32 `protobuf:"varint,5,opt,name=source_partition,json=sourcePartition,proto3" json:"source_partition,omitempty"`
	SourceOffset    int64 `protobuf:"varint,6,opt,name=source_offset,json=sourceOffset,proto3" json:"source_offset,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *LeaderboardEntry) Reset() {
	*x = LeaderboardEntry{}
	mi := &file_game_events_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaderboardEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaderboardEntry) ProtoMessage() {}

func (x *LeaderboardEntry) ProtoReflect() protoreflect.Message {
	mi := &file_game_events_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaderboardEntry.ProtoReflect.Descriptor instead.
func (*LeaderboardEntry) Descriptor() ([]byte, []int) {
	return file_game_events_proto_rawDescGZIP(), []int{8}
}

func (x *LeaderboardEntry) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *LeaderboardEntry) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *LeaderboardEntry) GetScore() int64 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *LeaderboardEntry) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *LeaderboardEntry) GetSourcePartition() int32 {
	if x != nil {
		return x.SourcePartition
	}
	return 0
}

func (x *LeaderboardEntry) GetSourceOffset() int64 {
	if x != nil {
		return x.SourceOffset
	}
	return 0
}

var File_game_events_proto protoreflect.FileDescriptor

const file_game_events_proto_rawDesc = "" +
	"\n" +
	"\x11game_events.proto\x12\agame.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\x87\x05\n" +
	"\tGameEvent\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x12\x1b\n" +
	"\tplayer_id\x18\x02 \x01(\tR\bplayerId\x12\x19\n" +
	"\bmatch_id\x18\x03 \x01(\tR\amatchId\x12;\n" +
	"\voccurred_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"occurredAt\x12\x1b\n" +
	"\x06region\x18\x05 \x01(\tH\x01R\x06region\x88\x01\x01\x12<\n" +
	"\rplayer_joined\x18\n" +
	" \x01(\v2\x15.game.v1.PlayerJoinedH\x00R\fplayerJoined\x126\n" +
	"\vplayer_left\x18\v \x01(\v2\x13.game.v1.PlayerLeftH\x00R\n" +
	"playerLeft\x12<\n" +
	"\rmatch_started\x18\f \x01(\v2\x15.game.v1.MatchStartedH\x00R\fmatchStarted\x126\n" +
	"\vmatch_ended\x18\r \x01(\v2\x13.game.v1.MatchEndedH\x00R\n" +
	"matchEnded\x12<\n" +
	"\rscore_changed\x18\x0e \x01(\v2\x15.game.v1.ScoreChangedH\x00R\fscoreChanged\x12<\n" +
	"\ritem_acquired\x18\x0f \x01(\v2\x15.game.v1.ItemAcquiredH\x00R\fitemAcquired\x12Q\n" +
	"\x14achievement_unlocked\x18\x10 \x01(\v2\x1c.game.v1.AchievementUnlockedH\x00R\x13achievementUnlockedB\a\n" +
	"\x05eventB\t\n" +
	"\a_region\"1\n" +
	"\fPlayerJoined\x12!\n" +
	"\fdisplay_name\x18\x01 \x01(\tR\vdisplayName\"?\n" +
	"\n" +
	"PlayerLeft\x12\x10\n" +
	"\x03won\x18\x01 \x01(\bR\x03won\x12\x1f\n" +
	"\vfinal_score\x18\x02 \x01(\x03R\n" +
	"finalScore\"A\n" +
	"\fMatchStarted\x12\x1d\n" +
	"\n" +
	"player_ids\x18\x01 \x03(\tR\tplayerIds\x12\x12\n" +
	"\x04mode\x18\x02 \x01(\tR\x04mode\"\xbb\x01\n" +
	"\n" +
	"MatchEnded\x12\x1d\n" +
	"\n" +
	"player_ids\x18\x01 \x03(\tR\tplayerIds\x12(\n" +
	"\x10winner_player_id\x18\x02 \x01(\tR\x0ewinnerPlayerId\x12)\n" +
	"\x10duration_seconds\x18\x03 \x01(\x03R\x0fdurationSeconds\x129\n" +
	"\n" +
	"started_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tstartedAt\"Y\n" +
	"\fScoreChanged\x12\x14\n" +
	"\x05delta\x18\x01 \x01(\x03R\x05delta\x12\x1b\n" +
	"\tnew_score\x18\x02 \x01(\x03R\bnewScore\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\"C\n" +
	"\fItemAcquired\x12\x17\n" +
	"\aitem_id\x18\x01 \x01(\tR\x06itemId\x12\x1a\n" +
	"\bquantity\x18\x02 \x01(\x05R\bquantity\"O\n" +
	"\x13AchievementUnlocked\x12 \n" +
	"\vachievement\x18\x01 \x01(\tR\vachievement\x12\x16\n" +
	"\x06detail\x18\x02 \x01(\tR\x06detail\"\xf3\x01\n" +
	"\x10LeaderboardEntry\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\tR\bplayerId\x12!\n" +
	"\fdisplay_name\x18\x02 \x01(\tR\vdisplayName\x12\x14\n" +
	"\x05score\x18\x03 \x01(\x03R\x05score\x129\n" +
	"\n" +
	"updated_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12)\n" +
	"\x10source_partition\x18\x05 \x01(\x05R\x0fsourcePartition\x12#\n" +
	"\rsource_offset\x18\x06 \x01(\x03R\fsourceOffsetB4Z2multiplayer-gaming/services/internal/gamepb;gamepbb\x06proto3"

var (
	file_game_events_proto_rawDescOnce sync.Once
	file_game_events_proto_rawDescData []byte
)

func file_game_events_proto_rawDescGZIP() []byte {
	file_game_events_proto_rawDescOnce.Do(func() {
		file_game_events_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_game_events_proto_rawDesc), len(file_game_events_proto_rawDesc)))
	})
	return file_game_events_proto_rawDescData
}

var file_game_events_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_game_events_proto_goTypes = []any{
	(*GameEvent)(nil),             // 0: game.v1.GameEvent
	(*PlayerJoined)(nil),          // 1: game.v1.PlayerJoined
	(*PlayerLeft)(nil),            // 2: game.v1.PlayerLeft
	(*MatchStarted)(nil),          // 3: game.v1.MatchStarted
	(*MatchEnded)(nil),            // 4: game.v1.MatchEnded
	(*ScoreChanged)(nil),          // 5: game.v1.ScoreChanged
	(*ItemAcquired)(nil),          // 6: game.v1.ItemAcquired
	(*AchievementUnlocked)(nil),   // 7: game.v1.AchievementUnlocked
	(*LeaderboardEntry)(nil),      // 8: game.v1.LeaderboardEntry
	(*timestamppb.Timestamp)(nil), // 9: google.protobuf.Timestamp
}
var file_game_events_proto_depIdxs = []int32{
	9,  // 0: game.v1.GameEvent.occurred_at:type_name -> google.protobuf.Timestamp
	1,  // 1: game.v1.GameEvent.player_joined:type_name -> game.v1.PlayerJoined
	2,  // 2: game.v1.GameEvent.player_left:type_name -> game.v1.PlayerLeft
	3,  // 3: game.v1.GameEvent.match_started:type_name -> game.v1.MatchStarted
	4,  // 4: game.v1.GameEvent.match_ended:type_name -> game.v1.MatchEnded
	5,  // 5: game.v1.GameEvent.score_changed:type_name -> game.v1.ScoreChanged
	6,  // 6: game.v1.GameEvent.item_acquired:type_name -> game.v1.ItemAcquired
	7,  // 7: game.v1.GameEvent.achievement_unlocked:type_name -> game.v1.AchievementUnlocked
	9,  // 8: game.v1.MatchEnded.started_at:type_name -> google.protobuf.Timestamp
	9,  // 9: game.v1.LeaderboardEntry.updated_at:type_name -> google.protobuf.Timestamp
	10, // [10:10] is the sub-list for method output_type
	10, // [10:10] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_game_events_proto_init() }
func file_game_events_proto_init() {
	if File_game_events_proto != nil {
		return
	}
	file_game_events_proto_msgTypes[0].OneofWrappers = []any{
		(*GameEvent_PlayerJoined)(nil),
		(*GameEvent_PlayerLeft)(nil),
		(*GameEvent_MatchStarted)(nil),
		(*GameEvent_MatchEnded)(nil),
		(*GameEvent_ScoreChanged)(nil),
		(*GameEvent_ItemAcquired)(nil),
		(*GameEvent_AchievementUnlocked)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_game_events_proto_rawDesc), len(file_game_events_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_game_events_proto_goTypes,
		DependencyIndexes: file_game_events_proto_depIdxs,
		MessageInfos:      file_game_events_proto_msgTypes,
	}.Build()
	File_game_events_proto = out.File
	file_game_events_proto_goTypes = nil
	file_game_events_proto_depIdxs = nil
}
