apiVersion: v1
kind: Secret
metadata:
  name: redpanda-secret
type: Opaque
stringData:
  cloud_storage_access_key: minio
  cloud_storage_secret_key: minio123
  iceberg_rest_catalog_client_id: catalog
  iceberg_rest_catalog_client_secret: catalog123
