# This secret contains all authentication credentials required for the lab:
#
# 1. cloud_storage_* keys: MinIO S3-compatible storage credentials for Redpanda
#    - Used by Redpanda brokers to store topic segments in MinIO buckets
#    - Matches the MinIO tenant configuration in minio-tenant-values.yaml
#
# 2. iceberg_rest_catalog_* keys: Authentication for Iceberg REST catalog
#    - Used by both Redpanda (for Iceberg sink connector) and Spark (for queries)
#    - Enables secure communication between components in the streaming pipeline
#
# Security Note: In production, use stronger passwords and consider external
# secret management (such as AWS Secrets Manager, HashiCorp Vault)
apiVersion: v1
kind: Secret
metadata:
  name: redpanda-secret
type: Opaque
stringData:
  cloud_storage_access_key: minio
  cloud_storage_secret_key: minio123
  iceberg_rest_catalog_client_id: catalog
  iceberg_rest_catalog_client_secret: catalog123
