# spark-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spark-iceberg
  namespace: iceberg-lab
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spark-iceberg
  template:
    metadata:
      labels:
        app: spark-iceberg
    spec:
      nodeSelector:
        kubernetes.io/hostname: kind-worker
      tolerations:
        - key: dedicated
          operator: Equal
          value: spark
          effect: NoSchedule
      containers:
        - name: spark
          image: spark-iceberg-jupyter:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8888
            - containerPort: 10000
          env:
            - name: AWS_ACCESS_KEY_ID
              value: minio
            - name: AWS_SECRET_ACCESS_KEY
              value: minio123
            - name: AWS_REGION
              value: local
