= Flatten JSON Messages
:page-layout: lab
:env-docker: true
:page-categories: Development, Stream Processing, Data Transforms
:description: Flatten JSON messages in topics using data transforms.
// Set up attributes to hold the latest version of Redpanda and Redpanda Console.
// For GitHub, hard-code the latest version to these values:
ifndef::env-site[]
:latest-redpanda-version: 23.3.5
:latest-console-version: 2.4.0
endif::[]
// For the docs site, use the built-in attributes that store the latest version as fetched from GitHub releases.
ifdef::env-site[]
:latest-redpanda-version: {full-version}
// All pages already have access to {latest-console-version} on the docs site.
endif::[]

This example uses Redpanda data transforms to take JSON messages in an input topic, flatten them using a customizable delimiter and produce the results to an output topic.

.Example input topic
```json
{
  "content": {
    "id": 123,
    "name": {
      "first": "Dave",
      "middle": null,
      "last": "Voutila"
    },
    "data": [1, "fish", 2, "fish"]
  }
}
```

.Example output topic with flattened JSON
```json
{
  "content.id": 123,
  "content.name.first": "Dave",
  "content.name.middle": null,
  "content.name.last": "Voutila",
  "content.data": [1, "fish", 2, "fish"]
}
```

== Prerequisites

You must have the following:

- At least version 1.20 of https://go.dev/doc/install[Go^] installed on your host machine.
- The link:https://docs.redpanda.com/current/get-started/rpk-install/[`rpk` command-line client].
+
Install `rpk` on your host machine and configure it to connect to your Redpanda cluster.
- https://docs.docker.com/compose/install/[Docker and Docker Compose] installed on your host machine.

== Limitations

- Arrays of objects are currently untested.
- Providing a series of objects as input, not an an array, may result
in a series of flattened objects as output.
- Due to how JSON treats floating point values, values such as `1.0` that can be converted to an integer will lose the decimal point. For example `1.0` becomes `1`.

== Run the lab

. Clone this repository:
+
```bash
git clone https://github.com/redpanda-data/redpanda-labs.git
```

. Change into the `data-transforms/flatten/` directory:
+
[,bash]
----
cd redpanda-labs/data-transforms/flatten
----

. Set the `REDPANDA_VERSION` environment variable to at least version 23.3.1. Data transforms was introduced in this version. For all available versions, see the https://github.com/redpanda-data/redpanda/releases[GitHub releases].
+
For example:
+
[,bash,subs="attributes+"]
----
export REDPANDA_VERSION={latest-redpanda-version}
----

. Set the `REDPANDA_CONSOLE_VERSION` environment variable to the version of Redpanda Console that you want to run. For all available versions, see the https://github.com/redpanda-data/redpanda/releases[GitHub releases].
+
For example:
+
[,bash,subs="attributes+"]
----
export REDPANDA_CONSOLE_VERSION={latest-console-version}
----

. Start Redpanda in Docker by running the following command:
+
```bash
docker compose up -d
```

. Set up your rpk profile:
+
```bash
docker exec -it redpanda-0 rpk profile create flatten --from-profile profile.yml
```

. Create the required topics `iss_json` and `iss_avro`:
+
```bash
docker exec -it redpanda-0 rpk topic create src sink
```

. Deploy the transforms function:
+
```bash
docker exec -it redpanda-0 rpk transform deploy --input-topic=src --output-topic=sink
```
+
This example accepts the following environment variables:
+
- `RP_FLATTEN_DELIM`: The delimiter to use when flattening the JSON fields. Defaults to `.`.
+
For example:
+
```bash
rpk transform deploy --var "RP_FLATTEN_DELIM=<delimiter>"
```

== Clean up

To shut down and delete the containers along with all your cluster data:

```bash
docker compose down -v
```


