= Owl Shop Example Application in Docker
:env-docker: true
:page-categories: Monitoring, Management
:description: Manage and monitor applications in Redpanda Console using data from an example e-commerce application called owl shop.
:page-layout: lab

This Docker Compose example starts a single Redpanda broker, Redpanda Console, and an example application called _owl shop_. Owl shop simulates a simple e-commerce shop that uses Redpanda as an asynchronous communication exchange. You can use the sample data to see how to manage and monitor applications in Redpanda Console. Owl shop creates topics, produces sample data to those topics, and consumes from those topics so that you can test Redpanda Console with some.

include::docker-compose:partial$docker-prerequisites.adoc[]

== Run the example

. xref:redpanda-labs:docker-compose:attachment$owl-shop/docker-compose.yml[Download] the following Docker Compose file on your local file system.
+
NOTE: If you are running on an ARM-based device such as the Apple M1 chip, uncomment the `platform: 'linux/amd64'` lines.
+
.Reveal the Docker Compose file
[%collapsible]
====
.`docker-compose.yml`
[,yaml,subs="attributes+"]
----
include::redpanda-labs:docker-compose:attachment$owl-shop/docker-compose.yml[]
----
====

. Run the following in the directory where you saved the Docker Compose file:
+
```bash
docker compose up -d
```

. Open Redpanda Console at http://localhost:8080[localhost:8080^] and go to *Topics* to see the owl shop topics.

include::docker-compose:partial$docker-customize.adoc[]

include::docker-compose:partial$docker-clean-up.adoc[]