= Transcode CSV Records to Avro Records
:page-layout: lab
:env-docker: true
:page-categories: Development, Stream Processing, Data Transforms
:description: Transcode CSV records to Avro using data transforms.
// Set up attributes to hold the latest version of Redpanda and Redpanda Console.
// For GitHub, hard-code the latest version to these values:
ifndef::env-site[]
:latest-redpanda-version: 23.3.5
:latest-console-version: 2.4.0
endif::[]
// For the docs site, use the built-in attributes that store the latest version as fetched from GitHub releases.
ifdef::env-site[]
:latest-redpanda-version: {full-version}
// All pages already have access to {latest-console-version} on the docs site.
endif::[]

This is an example of how to transcode CSV records to Avro records using Redpanda data transforms. The transforms function reads CSV
formatted records from an input topic, converts them to Avro encoded records based on the given schema, and writes them to an output topic.

== Prerequisites

You must have the following:

- At least version 1.20 of https://go.dev/doc/install[Go^] installed on your host machine.
- The link:https://docs.redpanda.com/current/get-started/rpk-install/[`rpk` command-line client].
+
Install `rpk` on your host machine and configure it to connect to your Redpanda cluster.
- https://docs.docker.com/compose/install/[Docker and Docker Compose] installed on your host machine.

== Run the lab

. Clone this repository:
+
```bash
git clone https://github.com/redpanda-data/redpanda-labs.git
```

. Change into the `data-transforms/to_avro/` directory:
+
[,bash]
----
cd redpanda-labs/data-transforms/to_avro
----

. Set the `REDPANDA_VERSION` environment variable to at least version 23.3.1. Data transforms was introduced in this version. For all available versions, see the https://github.com/redpanda-data/redpanda/releases[GitHub releases].
+
For example:
+
[,bash,subs="attributes+"]
----
export REDPANDA_VERSION={latest-redpanda-version}
----

. Set the `REDPANDA_CONSOLE_VERSION` environment variable to the version of Redpanda Console that you want to run. For all available versions, see the https://github.com/redpanda-data/redpanda/releases[GitHub releases].
+
For example:
+
[,bash,subs="attributes+"]
----
export REDPANDA_CONSOLE_VERSION={latest-console-version}
----

. Start Redpanda in Docker by running the following command:
+
```bash
docker compose up -d
```

. Set up your rpk profile:
+
```bash
docker exec -it redpanda-0 rpk profile create to_avro --from-profile profile.yml
```

. Create the topics to store the CSV and Avro records:
+
```bash
docker exec -it redpanda-0 rpk topic create nasdaq_history_csv
docker exec -it redpanda-0 rpk topic create nasdaq_history_avro
```

. Register the Avro schema:
+
```bash
# Create the schema
curl -s "http://localhost:18081/schemas/types" | jq .
# Post the schema
jq '. | {schema: tojson}' schema.avsc | \
   curl -X POST "http://localhost:18081/subjects/nasdaq_history_avro-value/versions" \
        -H "Content-Type: application/vnd.schemaregistry.v1+json" \
        -d @-
```
+
If the request is successful the version ID is returned. You'll pass this ID to the transforms function in the `SCHEMA_ID` environment variable later on. You can also find the version ID using the following command:
+
```shell
curl -s "http://localhost:53362/subjects/nasdaq_history_avro-value/versions" | jq .
```
+
Example output:
+
[.no-copy]
----
[
  1
]
----

. Deploy the transforms function:
+
```bash
docker exec -it redpanda-0 transform build
docker exec -it redpanda-0 transform deploy --var=SCHEMA_ID=1 \
                       --input-topic=nasdaq_history_csv \
                       --output-topic=nasdaq_history_avro
```
+
This example accepts the following environment variables:
+
- `SCHEMA_ID` (*required*): The ID of the Avro schema stored in the Redpanda schema registry.

. Produce CSV data:
+
```bash
cd test
./produce.sh HistoricalData_1692981579371.csv nasdaq_history_csv
```

. Consume CSV data:
+
```bash
docker exec -it redpanda-0 topic consume nasdaq_history_csv
```
+
The transforms function converts these CSV records to Avro and produces the results to the `consume nasdaq_history_avro` topic.

. Consume Avro data:
+
```bash
docker exec -it redpanda-0 topic consume nasdaq_history_avro
```

== Clean up

To shut down and delete the containers along with all your cluster data:

```bash
docker compose down -v
```
