apiVersion: v1
kind: Namespace
metadata:
  name: shadow
---
apiVersion: cluster.redpanda.com/v1alpha2
kind: Redpanda
metadata:
  name: redpanda
  namespace: shadow
spec:
  clusterSpec:
    image:
      tag: v25.3.4
    external:
      enabled: true
      service:
        enabled: false
      addresses:
        - localhost
    listeners:
      kafka:
        external:
          default:
            enabled: true
            port: 9094
            advertisedPorts:
              - 29094
    statefulset:
      replicas: 1
    config:
      cluster:
        default_topic_replications: 1
        enable_shadow_linking: true
    storage:
      tiered:
        config:
          cloud_storage_enabled: false
    tls:
      enabled: false
    auth:
      sasl:
        enabled: false
