apiVersion: cluster.redpanda.com/v1alpha2
kind: ShadowLink
metadata:
  name: shadow-link
  namespace: shadow
spec:

  # What cluster are we writing to?
  shadowCluster:
    staticConfiguration:
      kafka:
        brokers: ["redpanda.shadow.svc.cluster.local:9093"]
      admin:
        urls: ["http://redpanda.shadow.svc.cluster.local:9644/"]
      schemaRegistry:
        urls: ["http://redpanda.shadow.svc.cluster.local:8081/"]

  # What cluster are we reading from?
  sourceCluster:
    staticConfiguration:
      kafka:
        brokers: ["redpanda.source.svc.cluster.local:9093"]
      admin:
        urls: ["http://redpanda.source.svc.cluster.local:9644/"]
      schemaRegistry:
        urls: ["http://redpanda.source.svc.cluster.local:8081/"]

  # Replicate all topics (except for any that are pre-filtered)
  topicMetadataSyncOptions:
    interval: 5s
    autoCreateShadowTopicFilters:
      - name: '*'
        filterType: include
        patternType: literal

  # Replicate all consumer groups
  consumerOffsetSyncOptions:
    interval: 5s
    groupFilters:
      - patternType: literal
        filterType: include
        name: '*'

  # Replicate schema registry (using _schemas topic replication)
  schemaRegistrySyncOptions:
    schema_registry_shadowing_mode: "topic"
