== Customize the example

If you want to configure Redpanda or Redpanda Console, you need to customize the example Docker Compose file.

=== Configure Redpanda in Docker

To configure the Redpanda services with {docs-reference-base}node-properties.adoc[node configuration properties], you can do the following:

- Pass configuration properties to the `--set` option in the `redpanda start` command. For example:
+
[,yaml]
----
redpanda:
  command:
    - redpanda
    - start
    - --set pandaproxy_client.retries=6
----

- Create a `redpanda.yaml` file and mount it to the `/etc/redpanda/` directory on the `redpanda` containers. For example, if you create the `redpanda.yaml` file in a directory called `redpanda-mounts`, configure the following volume mounts:
+
[,yaml]
----
redpanda:
  volumes:
    - ./redpanda-mounts:/etc/redpanda/
----

=== Configure Redpanda Console in Docker

To configure the Redpanda Console service with {docs-reference-base}console/config.adoc[configuration properties], you can do the following:

* Use environment variables, for example:
+
[,yaml]
----
console:
  environment:
    KAFKA_RACKID: rack1
----

* Create a `redpanda-console-config.yaml` file and mount it to the `/etc/redpanda/` directory on the `redpanda-console` container. For example, if you create the `redpanda-console-config.yaml` file in a directory called `console-mounts`, configure the following volume mounts:
+
[,yaml]
----
console:
  volumes:
    - ./console-mounts:/etc/redpanda/
----